name: API Promotion suite 

on: 
  workflow_dispatch:
  
permissions:
   contents: read
   pages: write
   id-token: write
concurrency:
   group: 'pages'
   cancel-in-progress: true

jobs:
  dev_suite:
    environment:
        name: Dev suite deployment
        url: https://vllsag.github.io/analysts-demo/
    runs-on: self-hosted 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Run fuctional tests
        run: |
            cd tests
            k6 run functionalTest.js
        
      - name: Report results
        if: always()
        run: |
         mkdir results 
         cp index.html results 
         cp tests/summary-functional.html results
         
      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
             path: './results'
             
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v1
 
      - name: Promote to QA
        run: |
         curl -X POST -d '{"description": "Promotion Set to promote to QA environment","name":"PromoteToTest","destinationStages": ["f43f0fba-2ecd-4846-855e-b0de75f57eb0"],"promotedAssets": {"api": ["070111f2-befc-11ec-9621-df3e3620bc44"]}}' -H "Content-Type: application/json" -u ${{ secrets.username }}:${{ secrets.password }} https://analystsdemo.apigw-aw-eu.webmethods.io/rest/apigateway/promotion  
        
  qa_suite:
    environment:
        name: QA suite deployment
        url: https://vllsag.github.io/analysts-demo/index.html
    runs-on: self-hosted 
    needs: dev_suite
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run fuctional tests
        run: |
            cd tests
            k6 run functionalTest.js

      - name: Run Performance tests
        run: |
            cd tests
            k6 run performanceTest.js
        
      - name: Report results
        if: always()
        run: |
         mkdir results 
         cp index-performance.html results/index.html
         cp tests/summary.html  results 
         cp tests/summary-functional.html results
         
      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
             path: './results'
             
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v1
 
      - name: Promote to Prod
        run: |
         curl -X POST -d '{"description": "Promotion Set to promote to Prod environment","name":"PromoteToProd","destinationStages": ["6993504b-afd6-450d-a4ec-076a151e34e4"],"promotedAssets": {"api": ["070111f2-befc-11ec-9621-df3e3620bc44"]}}' -H "Content-Type: application/json" -u ${{ secrets.username }}:${{ secrets.password }} https://demofreeforever.apigw-aw-eu.webmethods.io/rest/apigateway/promotion  
         
