name: Performance test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: RUN functional tests
        run:  k6 run functionalTests.js
        
      - name: RUN performanceTests.js
        run: k6 run performanceTests.js
        
      - name: uploading html report 
        run: uploading html report 

