name: Performance test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#update urls 
      - name: RUN functional tests
        run:  k6 run functionalTests.js
#update urls         
      - name: RUN performanceTests.js
        run: k6 run performanceTests.js
#promotion step 
      - name: "Put back details"
        uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          GITHUB_TOKEN: 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
          branch: main
          commit_message: "Automated Change"
          push_options: '--force'
          create_branch: true 

