name: Performance test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo statement
        run:  echo "hi"

